name: Notify github activity on discord

on:
  repository_dispatch:
    types: [org-workflow-bot]  # <-- requirement to trigger central workflows

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
